#!/bin/bash

set -x

set -eo pipefail

# This 'build' script is where you can add steps that should be run when
# building the image for your custom workshop.

# Move the workshop content to '/opt/app-root/workshop'. It could be left
# at it's default location of '/opt/app-root/src/workshop', but by moving it,
# it is out of view of the user doing the workshop and they aren't likely to
# delete it by accident and break the display of the workshop content.

mv workshop /opt/app-root/workshop

# Also delete some of the other files from the top of the Git repository we
# don't need for running the workshop.

rm -f Dockerfile README.md LICENSE resources

# If the workshop requires Git, it is necessary to set some defaults for
# the name and email of the user for Git.

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

# Install kpack utilities.

curl -sL -o /tmp/logs-linux.tgz https://github.com/pivotal/kpack/releases/download/v0.0.5/logs-v0.0.5-linux.tgz

tar -C /opt/app-root/bin -xf /tmp/logs-linux.tgz

rm -rf /tmp/logs-linux.tgz
