#!/bin/bash

# This 'setup' script is where you can add steps that should be run each
# time the container for the workshop is started. Note that if you are
# using persistent storage with a workshop and make changes to files from
# this script, or are deploying applications, your scripts must cope with
# the steps having already been run. This is because this script will be
# run a second time if the container were restarted for some reason.

# Fill in the address of the local image registry deployed to the project.

cat sample-java-app.yaml.in | envsubst > sample-java-app.yaml
